apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.ports.api }}
      targetPort: {{ .Values.service.ports.api }}
    - name: console
      port: {{ .Values.service.ports.console }}
      targetPort: {{ .Values.service.ports.console }}
