replicaCount: 1

image:
  repository: quay.io/minio/minio
  tag: latest
  pullPolicy: IfNotPresent

minioArgs:
  - server
  - /data
  - "--console-address"
  - ":9001"

env:
  rootUser: admin
  rootPassword: admin123

service:
  type: ClusterIP
  annotations: {}
  ports:
    console: 9000
    api: 9001
    
persistence:
  enabled: false
  existingClaim: ""
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClass: ""

routes:
  enabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    certificate: ""
    key: ""
    caCertificate: ""
    destinationCACertificate: ""
  console:
    host: ""
    annotations: {}
  api:
    host: ""
    annotations: {}

argocdProject:
  enabled: true
  name: argo-workshop-quarkus-hello_quarkus
  namespace: openshift-gitops
  description: Argo CD project for camel-quarkus workshop deployment
  sourceRepos:
    - https://github.com/na-launch-workshop/workshop-quarkus-using_camel.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist: []


# Easy knobs for tuning
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
