replicaCount: 1

image:
  repository: quay.io/minio/minio
  tag: latest
  pullPolicy: IfNotPresent

minioArgs:
  - server
  - /data
  - "--console-address"
  - ":9001"

env:
  rootUser: admin
  rootPassword: admin123

service:
  type: ClusterIP
  annotations: {}
  ports:
    api: 9000
    console: 9001
    
persistence:
  enabled: false
  existingClaim: ""
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClass: ""

routes:
  enabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    certificate: ""
    key: ""
    caCertificate: ""
    destinationCACertificate: ""
  console:
    host: ""
    annotations:      
      app.openshift.io/route-url: "https://{{ .Release.Name }}-console-{{ .Release.Namespace }}.{{ .Values.routes.tls.termination | default \"apps\" }}.{{ .Values.global.clusterDomain | default \"{{ .Release.Service }}\" }}"
  api:
    host: ""
    annotations: {}

# Easy knobs for tuning
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
